spring:
  application:
    name: entry-task
  task:
    scheduling:
      pool:
        size: 30
server:
  port: 7173
  servlet:
    context-path: /entry-task

system:
  id: "${REALM:browser-task}"
  database-json-url: "${DATABASE_JSON_URL:***onpet.vn/public/api/dynamic/table}"
  email-profile: "${EMAIL:tylertruong24@gmail.com}"
  headless-mode: "${HEADLESS_MODE:false}"
  disable-keep-alive-profile: "${DISABLE-KEEP-ALIVE-PROFILE:false}"
  callback-url: "${CALLBACK_URL:***}"

profile-folder:
  user-profile: "${CLOUD_SHELL_CHROME_PROFILE_FOLDER:entry-task-chrome-profiles-download-extract}"
  user-profile-download: "${CLOUD_SHELL_CHROME_PROFILE_DOWNLOAD_FOLDER:entry-task-chrome-profiles-download}"

github:
  api-url: "${GITHUB_API_URL:https://api.github.com/repos/{{owner}}/{{repo_name}}/contents}"
  token: "${GITHUB_TOKEN: your github token}"

logging:
  file:
    name: log/entry-task.log
  logback:
    rollingpolicy:
      max-history: 2
