spring:
  application:
    name: entry-task
server:
  port: 7173
  servlet:
    context-path: /entry-task

system:
  id: "${REALM:browser-task}"
  profile-table-url: "${PROFILE_TABLE_URL: your url to save profile after login success}"
  email-profile: "${EMAIL:tyler.truong0216@gmail.com}"

github:
  api-url: "${GITHUB_API_URL:https://api.github.com/repos/{{owner}}/{{repo_name}}/contents}"
  token: "${GITHUB_TOKEN: your github token}"